export const DEPARTMENTS = [
    { value: "1", label: "Amazonas", lat: -5.00, lon: -78.225, zoom: 7.5 },
    { value: "2", label: "Áncash", lat: -9.40, lon: -77.70, zoom: 8 },
    { value: "3", label: "Apurímac", lat: -14.00, lon: -72.85, zoom: 8.5 },
    { value: "4", label: "Arequipa", lat: -15.925, lon: -72.45, zoom: 7.75 },
    { value: "5", label: "Ayacucho", lat: -13.90, lon: -74.25, zoom: 7.75 },
    { value: "6", label: "Cajamarca", lat: -6.15, lon: -78.85, zoom: 7.75 },
    { value: "7", label: "Callao", lat: -12.05, lon: -77.15, zoom: 11 },
    { value: "8", label: "Cusco", lat: -13.30, lon: -71.96, zoom: 7.25 },
    { value: "9", label: "Huancavelica", lat: -13.05, lon: -75.05, zoom: 8.25 },
    { value: "10", label: "Huánuco", lat: -9.35, lon: -75.85, zoom: 8.25 },
    { value: "11", label: "Ica", lat: -14.20, lon: -75.60, zoom: 8 },
    { value: "12", label: "Junín", lat: -11.65, lon: -75.00, zoom: 8 },
    { value: "13", label: "La Libertad", lat: -7.95, lon: -78.35, zoom: 8 },
    { value: "14", label: "Lambayeque", lat: -6.30, lon: -79.80, zoom: 8.25 },
    { value: "15", label: "Lima", lat: -11.80, lon: -76.71, zoom: 7.75 },
    { value: "16", label: "Loreto", lat: -4.25, lon: -74.50, zoom: 6.25 },
    { value: "17", label: "Madre de Dios", lat: -11.60, lon: -70.80, zoom: 7.5 },
    { value: "18", label: "Moquegua", lat: -16.90, lon: -70.95, zoom: 8.5 },
    { value: "19", label: "Pasco", lat: -10.30, lon: -75.075, zoom: 8.25 },
    { value: "20", label: "Piura", lat: -5.20, lon: -80.275, zoom: 8 },
    { value: "21", label: "Puno", lat: -15.05, lon: -70.10, zoom: 7.25 },
    { value: "22", label: "San Martín", lat: -7.05, lon: -76.90, zoom: 7.75 },
    { value: "23", label: "Tacna", lat: -17.55, lon: -70.25, zoom: 8.75 },
    { value: "24", label: "Tumbes", lat: -3.815, lon: -80.49, zoom: 9.5 },
    { value: "25", label: "Ucayali", lat: -9.30, lon: -73.875, zoom: 7.25 }
]

export const EVENT_TYPES = [
    { value: 'precipitacion', label: '🌧️ Precipitación' },
    { value: 'sequia', label: '☀️ Sequía' },
    { value: 'deficit_hidrico', label: '🏜️ Déficit Hídrico' },
    { value: 'inundacion', label: '🌊 Inundación' },
    { value: 'el_nino', label: '🌡️ El Niño' },
    { value: 'helada', label: '❄️ Helada' },
    { value: 'friaje', label: '🥶 Friaje' },
    { value: 'huaico', label: '🪨 Huaico' },
    { value: 'vientos_fuertes', label: '🌬️ Vientos Fuertes' },
    { value: 'nevada', label: '🌨️ Nevada' },
    { value: 'veranillo', label: '🌤️ Veranillo' },
    { value: 'ola_de_calor', label: '🔥 Ola de Calor' },
    { value: 'ola_de_frio', label: '🧊 Ola de Frío' },
    { value: 'huracan', label: '🌀 Huracán' },
    { value: 'ciclon', label: '🌪️ Ciclón' },
    { value: 'tormenta', label: '⚡ Tormenta' },
    { value: 'granizada', label: '🌨️ Granizada' },
    { value: 'incendio', label: '🌲 Incendio' },
    { value: 'plaga_agricola', label: '🐛 Plaga Agrícola' },
    { value: 'otros', label: '🍂 Otros' },
];

export const RISK_LEVELS = [
    { value: 'MUY ALTO', label: '🔴 Muy Alto' },
    { value: 'ALTO', label: '🟠 Alto' },
    { value: 'MEDIO', label: '🟡 Medio' },
    { value: 'BAJO', label: '🟢 Bajo' },
    { value: 'MUY BAJO', label: '🔵 Muy Bajo' },
];